# 공통 영역
spring:
  profiles:
    active: local

# local 환경 영역
---
spring:
  profiles: local
  datasource:
    data: classpath:defaultData-h2.sql  # 애플리케이션 실행 시 default로 insert할 쿼리 데이터 파일
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:h2:~/apps/h2db/crm
  jpa:
    show-sql: true  # sql 쿼리 디버깅 로그 표현
    hibernate:
      ddl-auto: create-drop # 애플리케이션 실행 시 마다 테이블을 drop 후 create함
  h2:
    console:
      enabled: true
  mvc:    view:
      prefix: /WEB-INF/views/ # viewResolver 설정 view 파일을 읽어들일 폴더를 설정함 *.jsp는 반드시 /webapp/WEB-INF/ 경로에서만 인식되는 특성이 있음      suffix: .jsp